name: Run tests with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Test with Maven
        run: mvn text
      - name: Standard Checkout
        uses: actions/checkout@v2